### ISSUE TITLE
Feature Request: get string by locale without set app locale

### ISSUE THREAD

**Issue by shantanu-csedu** [phrase/phrase-android#32]
It will be helpful if Phrase add support to get string for multiple locale for the same time. Like the following code

`Phrase.getString(key, locale)`

In my case, there are background tasks to generate report (pdf) in multiple language. If I set `Phrase.setLocaleCode(locale)` before the task then user will see the UI in different language.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-android) and we can take more direct action toward finding a solution.
