### ISSUE TITLE
Switching from Dark to Light mode crashes the app 

### ISSUE THREAD

**Issue by pagsantos** [phrase/phrase-android#38]
if we switch from Light To Dark mode we get our app to crash. 

I think this is happening to all apps that implement this SDK 
```
at androidx.appcompat.app.AppCompatDelegateImpl.applyDayNight(AppCompatDelegateImpl.java:2389)
        at androidx.appcompat.app.AppCompatDelegateImpl.onConfigurationChanged(AppCompatDelegateImpl.java:666)
        at androidx.appcompat.app.PhraseBaseAppCompatDelegate.onConfigurationChanged(SourceFile:1)
```
# Tested on:
Android 12 
Happens on Real devices as well as Emulator 
Version Phrase SDK used 'com.github.phrase:android-sdk:3.1.2'

**Comment by RogerParis** [comment]
@subspider I couldn't reproduce this on our test project. Is it a crash or an Application Not Responding problem? And if it is a crash, could you tell me the steps you follow to reproduce it? Do you see the crash when going back to the application or directly when selecting the dark mode?

**Comment by vlylozianSixt** [comment]
@RogerParis we integrate our app with the instructions provided here: https://help.phrase.com/help/android-sdk-installation-instructions.

The steps to reproduce:
- Run the app with integrated SDK
- Switch to dark mode or light mode from the swipe down menu
- The app freezes for a moment
- After a second or two the app crashes

The main cause I suspect is the getDelegate override method in our `BaseActivity`:

```
override fun getDelegate(): AppCompatDelegate {
    return Phrase.getDelegate(this, super.getDelegate())
}
```

**Comment by Savrov** [comment]
+1

**Comment by kabirkhaan** [comment]
Regrettably, this issue remains unresolved, and it is with a heavy heart that I communicate this. This persistent problem has placed us in an untenable position, impeding our ability to implement the vital Phrase OTA feature. Our application's multilingual support for over 20 diverse languages is contingent upon the successful resolution of this issue.

The gravity of the situation has become even more pronounced as we recently found ourselves grappling with urgent situations that necessitated swift action due to translation-related concerns. These exigencies forced us to resort to creating hotfixes, which is far from an optimal approach.

Given the circumstances, I implore you to consider the criticality of this matter. Prioritizing the resolution of this issue would be a game-changer for us. The capability to roll out the OTA feature would greatly alleviate our current challenges and significantly enhance the functionality and stability of our application. Your swift attention to this matter would be immensely appreciated.

**Comment by jan-reehuis-apploft** [comment]
@kabirkhaan Unfortunately, we can still not reproduce the issue with our internal testing app. Could you provide a full stack trace?
With v3.3.1 an essential fix for the internal resource handling was implemented and might also affect this issue. Which version(s) have you tested?

**Comment by theSoenke** [comment]
Hi @MyrraWey0, thanks for the stacktrace. In your reply you mention version 3.1.3 or do you mean 3.3.1?

**Comment by MyrraWey0** [comment]
Hi @theSoenke, play market version used 3.1.3. We updated Phrase App version to 3.7.2 but this version still not published, so I can't provide information regarding latest lib version.

**Comment by theSoenke** [comment]
Hey @MyrraWey0, could you check whether you're using the new Maven repository https://maven.download.phrase.com? Since 3.5.0 we're publishing to our own Maven repository as we had some issues with jitpack in the past. The instructions are listed in the release notes: https://github.com/phrase/phrase-android/releases/tag/3.5.0

**Comment by MyrraWey0** [comment]
@theSoenke, for affected version we use old repository. New repository used in unpublished version, so we will have any update regarding it in few months.
