### ISSUE TITLE
Add support to Android 13 (API 33) in-app language change

### ISSUE THREAD

**Issue by antygravity** [phrase/phrase-android#49]
We use Phase in our project.
Currently we are implementing in-app language change (https://developer.android.com/guide/topics/resources/app-languages) which is officially supported in Appcompat  1.6.0-rc01 or  1.7.0-alpha01.
This works fine with sdk < 33, but on Tiramisu AppCompatDelegate.getApplicationLocales() doesn't return locale code.
To fix it I added a workaround: 
`   override fun getDelegate(): AppCompatDelegate {

        return if (Build.VERSION.SDK_INT >= TIRAMISU) {

            super.getDelegate()

        } else {

            Phrase.getDelegate(this, super.getDelegate())

        }
    }`
Can You add support to in-app language change using Appcompat so we can remove this hack?

**Comment by protiucandrei** [comment]
Any updates on this?

I am having the same issue for all APIs when using AndroidX APIs for backward and forward compatibility.

**Comment by MehdiBrahmi** [comment]
Hello Phrase,

Could you kindly provide an update on the progress or any potential timelines for its issue  which was opened nearly a year ago. As it significantly impacts our application's functionality.

Additionally, we would appreciate further clarification regarding the functioning of the Phrase SDK without the `getDelegate()` method override. Without this override, we are uncertain about how the SDK Phrase will work. Could you provide more details on this aspect?

Your assistance and information would be greatly appreciated.
Thank you in advance,
Mehdi

**Comment by theSoenke** [comment]
Hi,

Overwriting `getDelegate` is required to hook into the view creation as `Activity` delegates it to `AppCompatDelegate`. The view creation needs to be modified to point the XML reference to the translations fetched from the Resources. Otherwise the XML view inflation would be using the bundled assets, which are final and cannot be changed.

Still overwriting `getDelegate` causes the issue with per-app language preferences as it did not use the selected language.

The 3.7.0 release tried to address using the selected locale but it turns out it will require some further changes. We’re working on solving the additional cases and plan to release them in 1-2 weeks.

**Comment by theSoenke** [comment]
Hi,

we have released version [3.7.4](https://github.com/phrase/phrase-android/releases/tag/3.7.4), which should correctly use the App Locale from the system settings. The locale is chosen based on the following priority: 
1. Custom locale. If set in `Phrase.setup` or `Phrase.setLocaleCode`
2. App locale in system settings (supported since Android 13)
3. System locale

When debug mode is enabled with `PhraseLog.setLogLevel(Severity.Debug);` the logs will also show whenever a locale is changed in the settings:

<img width="710" alt="locale-log" src="https://github.com/phrase/phrase-android/assets/1757301/65a5a8fb-a6d1-4637-8d2e-59483fc4e9ea">

With this version changing the per-app locale in the system settings should now work as intended. But please let me know if there are still any open questions!

**Comment by theSoenke** [comment]
The final missing part for full per-app preferences has been added in 3.9.0 https://github.com/phrase/phrase-android/releases/tag/3.9.0
